# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Luke Evans"
title_separator          : "-"
name                     : &name "Luke Evans"
description              : &description "Ecologist | Quantitative Conservation | Decision Support"
url                      : "https://lukeevans603.github.io"  # <-- Replace with your actual GitHub Pages URL
baseurl                  : "" 
repository               : "lukeevans603/lukeevans603.github.io"  # <-- Replace with your actual repo name

author:
  avatar           : "profile.png"  # Upload this to /images/ or replace with your actual image
  name             : "Luke Evans"
  pronouns         : "he/him"
  bio              : "Quantitative ecologist focused on invasive species, structured decision-making, and conservation science."
  location         : "Gainesville, FL USA"
  employer         : "University of Florida"

  email            : "lukeevans@ufl.edu"  # <-- Replace with your email
  googlescholar    : "https://scholar.google.com/citations?user=9jYlHVgAAAAJ&hl=en"  # Replace with your profile
  orcid            : "https://orcid.org/0000-0002-6618-4733"  # Replace with your ORCID
  pubmed           : 
  github           : "lukeevans603"
  linkedin         : "https://www.linkedin.com/in/luke-evans-17b16a27/"
 # twitter          : "yourhandle"  # If applicable
